// lib/services/hotkey_service.dart

import 'dart:io';
import 'package:flutter/material.dart';

class HotkeyService {
  static Future<bool> registerTriggers({
    required String primaryTrigger,
    required String secondaryTrigger,
  }) async {
    if (!Platform.isLinux) {
      return true; // Non-Linux fallback
    }

    try {
      final home = Platform.environment['HOME'] ?? '';
      final omojiBin = '$home/.local/bin/omoji';

      final primaryGsettings = _convertToGsettingsFormat(primaryTrigger);
      final secondaryGsettings = _convertToGsettingsFormat(secondaryTrigger);

      // Create a script that registers custom keybindings in GNOME/dconf
      final scriptFile = File('$home/.config/omoji/register_hotkeys.sh');
      if (!await scriptFile.parent.exists()) {
        await scriptFile.parent.create(recursive: true);
      }

      final scriptContent = '''#!/bin/bash
# Automatically generated by Omoji Hotkey Registration

OMOTI_BIN="$omojiBin"
PRIMARY_BINDING="$primaryGsettings"
SECONDARY_BINDING="$secondaryGsettings"

if command -v gsettings >/dev/null 2>&1; then
    PRIMARY_PATH="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/omoji-primary/"
    SECONDARY_PATH="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/omoji-secondary/"

    # Set Primary Shortcut
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$PRIMARY_PATH name "Omoji Launcher (Primary)" 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$PRIMARY_PATH command "\$OMOTI_BIN" 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$PRIMARY_PATH binding "\$PRIMARY_BINDING" 2>/dev/null || true

    # Set Secondary Shortcut
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$SECONDARY_PATH name "Omoji Launcher (Secondary)" 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$SECONDARY_PATH command "\$OMOTI_BIN" 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$SECONDARY_PATH binding "\$SECONDARY_BINDING" 2>/dev/null || true

    # Add both paths to custom-keybindings list if not present
    CURRENT_LIST=\$(gsettings get org.gnome.settings-daemon.plugins.media-keys custom-keybindings 2>/dev/null)
    if [[ "\$CURRENT_LIST" != *"\$PRIMARY_PATH"* ]]; then
        if [ "\$CURRENT_LIST" == "@as []" ] || [ -z "\$CURRENT_LIST" ]; then
            gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['\$PRIMARY_PATH', '\$SECONDARY_PATH']" 2>/dev/null || true
        else
            NEW_LIST=\$(echo "\$CURRENT_LIST" | sed "s|]|\, '\$PRIMARY_PATH', '\$SECONDARY_PATH']|")
            gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "\$NEW_LIST" 2>/dev/null || true
        fi
    fi
fi
''';

      await scriptFile.writeAsString(scriptContent);
      await Process.run('chmod', ['+x', scriptFile.path]);
      final result = await Process.run('bash', [scriptFile.path]);

      return result.exitCode == 0;
    } catch (e) {
      debugPrint('Failed to register system hotkeys: $e');
      return false;
    }
  }

  static String _convertToGsettingsFormat(String input) {
    String clean = input.trim();
    if (clean.isEmpty) return '<Super>period';

    clean = clean.replaceAll('Super', '<Super>');
    clean = clean.replaceAll('Cmd', '<Super>');
    clean = clean.replaceAll('Ctrl', '<Primary>');
    clean = clean.replaceAll('Control', '<Primary>');
    clean = clean.replaceAll('Alt', '<Alt>');
    clean = clean.replaceAll('Shift', '<Shift>');
    clean = clean.replaceAll('+', '');
    clean = clean.replaceAll(' ', '');
    clean = clean.replaceAll('.', 'period');
    clean = clean.replaceAll(',', 'comma');
    clean = clean.replaceAll('/', 'slash');
    clean = clean.replaceAll('-', 'minus');
    clean = clean.replaceAll('Space', 'space');

    return clean.replaceAllMapped(RegExp(r'(>)([A-Z])$'), (match) {
      return '${match.group(1)}${match.group(2)!.toLowerCase()}';
    });
  }
}
